mappings:
  - name: 'r1'
    listenPort: 9300 # 监听端口
    forwardHost: "qw607.com" # 转发目标域名
    forwardPort: 80 # 转发目标端口
    console:
      printRequest: false # 是否打印转发信息
      printResponse: false # 是否打印转发信息
    dump:
      enable: true # 是否开启转发数据包dump
      dumpPath: "D:\\JAVA_WORK_SPACE\\jmagnifier\\target" # dump数据包存放路径